spring:
   datasource:
      username: movie_finalproj
      password: movie_finalproj
      url: jdbc:mysql://localhost:3306/movie_finalproj
      
   jpa:
      hibernate:
         ddl-auto: none
      show-sql: true
      
   sql:
      init:
         mode: never